### PR TITLE
add HalfEdges.jl

### PR DESCRIPTION
**Pull request by mewertd2**

### CODE REVIEW

**Comment by PetrKryslUCSD** [comment]
Is that it? I thought you had  half a dozen or so of relevant packages on github?

**Comment by mewertd2** [comment]
I've actually rolled a few packages into 3.  Easier to maintain that way.
https://github.com/digitaldomain/DiscreteDifferentialGeometry.jl is definitely relevant.   Which section should that be added to? 

https://github.com/digitaldomain/Multivectors.jl is a geometric algebra package that doesn't have any special considerations for PDE's.  So I'd say that is probably too general for a PDE survey.

**Comment by PetrKryslUCSD** [comment]
Perhaps the geometry and topology section?

**Comment by mewertd2** [comment]
Looks good.  Thanks.

**Pull request merged**
